finish first homework
Belocherkovec/2024-2-VK-EDU-Frontend-N-Kobyakov pull request #1
Opened 2024-09-23 08:21 UTC by Belocherkovec

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin и @nelkor.

Что было сделано:
* Создан pull_request_template.
* Выполнено первое дз.
* Написаны тесты для первого дз.

2024-09-23 11:07 UTC, nelkor requested changes

2024-09-23 11:07 UTC, nelkor commented on convertBytesToHuman.js
> +    bytes === null ||
Это проверяется за один вызов `Number.isFinite`.

2024-09-23 11:07 UTC, nelkor commented on convertBytesToHuman.js
> +  let byteUnits = ['B', 'kB', 'MB', 'GB', 'TB']
`byteUnits` не переопределяется, следует объявить переменную, как `const`.

2024-09-23 11:07 UTC, nelkor commented on correctSentence.js
> +  if (typeof text !== 'string') return ERROR_MESSAGE;
Тогда хотя бы не `return`, а `throw new Error`. Потому что я тебя что 'ERROR! Invalid arguments.' строка, что обычный ответ функции — тоже строка. Как узнать, что произошла ошибка?)

2024-09-23 11:07 UTC, nelkor commented on nonUniqueElements.js
> +  ) return ERROR_MESSAGE;
Тут тоже лучше будет `throw new Error`, но уже не так критично, потому что уже хотя бы есть разница в типах.

2024-09-24 06:20 UTC, nelkor approved these changes
Отлично! Очень элегантное решение с `+bytes.toFixed(2)`, отсекающим лишнюю дробную часть.

2024-09-25 21:02 UTC, HaseProgram approved these changes
12!

2024-09-25 21:02 UTC, merged