Homework 2
Belocherkovec/2024-2-VK-EDU-Frontend-N-Kobyakov pull request #2
Opened 2024-09-29 16:20 UTC by Belocherkovec

# Домашнее задание № 2

Прошу @martinkomitsky, @haseprogram, @kgrechin или @nelkor.

Что было сделано:
* Настроен код стайл для всего проекта
* Настроен webpack
* Сделана верстка страницы по заданию
* Реализация сообщений и ввода на веб-компонентах
* Реализация удаления сообщений

2024-09-30 16:34 UTC, nelkor requested changes
Надо добавить возможность писать от имени нескольких пользователей. Сообщения других пользователей должны быть подписаны.

При удалении одного сообщения (из середины) удаляются сразу несколько.

Папка `build` должна быть в игноре.

На текущий момент код выглядит хорошо, очень крутое решение на шадоу-доме. Но надо доделать.

2024-09-30 16:34 UTC, nelkor commented on simple-chat/src/components/MessagesList/MessagesList.js
> +  // disconnectedCallback() {}
В финальной версии не должно быть закомментированных кусков кода.

2024-09-30 16:34 UTC, nelkor commented on simple-chat/src/components/MessagesList/MessagesList.module.css
> +  /* min-height: calc(100vh - 60px - 43px); */
Это туда же.

2024-10-03 13:01 UTC, nelkor approved these changes
Первый!

2024-10-03 18:09 UTC, HaseProgram approved these changes
12!

2024-10-03 18:10 UTC, merged