Hw 5
Belocherkovec/2024-2-VK-EDU-Frontend-N-Kobyakov pull request #5
Opened 2024-10-24 19:42 UTC by Belocherkovec

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @nelkor.

ghPages: https://belocherkovec.github.io/2024-2-VK-EDU-Frontend-N-Kobyakov/

Что было сделано:
* Переписал приложение на React + TS
* Реализовал srote через контекст
* Реализовал роутинг без библиотек
* Избавился от старого варианта подключения иконок
* Переписал стили на scss

2024-10-25 11:28 UTC, nelkor requested changes
Галочка не становится двойной после того, как сообщение прочитали.

Отметка о новом сообщении не пропадает после прочтения этого сообщения.

Плейсхолдер на ввод сообщения: "Сначала вы должны ввести имя".

2024-10-25 11:28 UTC, nelkor commented on reactChat/src/shared/consts/index.ts
> +// export {MessageStatuses} from './statuses';
Енумы лучше не использовать, с ними много разнообразных проблем. Думаю, этот случай также просто из-за факта использования енума.

Не должно быть закомментированного кода в готовом задании.

2024-10-25 11:28 UTC, nelkor commented on reactChat/src/pages/Dialog/dialog.module.scss
> +// }
То же самое, не должно быть закомментированного кода.

2024-10-26 11:23 UTC, nelkor approved these changes

2024-10-27 17:49 UTC, merged

2024-10-27 17:49 UTC, martinkomitsky commented
12!