Hw 7
Belocherkovec/2024-2-VK-EDU-Frontend-N-Kobyakov pull request #7
Opened 2024-11-18 14:53 UTC by Belocherkovec

# Домашнее задание № 7, 9, 10.

!!! В этом домашнем задании реализованы требования из дз 7 (перевести текущий функционал на использование API), из дз 9 (подключить к проекту state-manager, работу с данными переделать с учетом использования state-manager), из дз 10 (приватный роутинг, авторизация).

Прошу @martinkomitsky, @haseprogram, @kgrechin или @nelkor.

gh-pages: https://belocherkovec.github.io/2024-2-VK-EDU-Frontend-N-Kobyakov

Что было сделано:
- Подключил и настроил библиотеку Axios.
- Сверстал страницу авторизации.
- Сделал универсальный компонент <Input/> с валидацией и подсветкой ошибок. Валидация реализована через validityState.
- У input type=«password» доступно переключение видимости вводимого пароля.
- Сделал PrivateRoute, для разграничения доступа неавторизованным пользователям.
- Подключил и настроил библиотеку redux на проекте.
- Реализовал интерсепторы для добавления токена в запросы и для обновления токена.
- Cостояние аутентификации отслеживается через slice юзера в store. Реддирект на страницу чатов со страницы авторизации если пользователь авторизован.
- Вынес path для роутов в отдельную константу.
- Сверстал страницу создания нового диалога, вывел список пользователей с Использованием API.
- Вынес логику инициализации приложения в отдельный компонент.
- Реализовал страницу чатов с использованием реального API.
- Реализовал страницу диалога, отправку сообщений с использованием реального API.
- Все данные записываются в redux-store.
- Реализовал обработку событий centrifugo. Сообщения в открытом диалоге обновляют статус, добавляются и т.п.

2024-11-19 15:35 UTC, kgrechin commented
> @HaseProgram @kgrechin что будем делать с этим реквестом? Ни сроков не понять, ни какое где ДЗ, и все пункты тяжело понять, выполнены ли 

мне @Belocherkovec говорил, что вроде как утряс все моменты и разрешили сдать так)

2024-11-19 19:10 UTC, Belocherkovec commented
> @HaseProgram @kgrechinчто будем делать с этим ревестом? Ни сроков не понять, ни где ДЗ, и все пункты тяжело понять, выполнить ли

Скорректировал описание PR, чтобы проще было понять, какие пункты и в рамках какого ДЗ реализованы.

2024-11-20 12:31 UTC, nelkor requested changes
В основном, пролистал код, потому что его очень много : )
Самый бросающийся в глаза недочёт — по импортам. Отметил ещё пару мест в коде, ну и плюс баги.

### Замеченные баги

Незарегистрированного пользователя ждёт разочарование. Он никак не сможет войти.

При добавлении нового чата не работает поиск.

Во время добавления нового чата при нажатии на пользователя ничего не происходит. Приходится возвращаться на главный экран и там уже виден добавленный чат.

2024-11-20 12:31 UTC, nelkor commented on reactChat/src/app/AppInit.tsx
> +} from '@/shared/api/centrifugo/types';
Если мы импортируем что-то в `app` из `shared`, то импорты должны выглядеть так:

`import { первое, второе, третье } from '@/shared'`

То есть `shared` должен ре-экспортировать всё, что можно импортировать из других слоёв.

Это касается всех слайсов. Например, не может быть двух импортов из "@/entities/User/что-то-разное". Должен быть `import { что, то, разное} from '@/entities/User'`

И это касается не только этого файла, а вообще всех импортов в репозитории.

2024-11-20 12:31 UTC, nelkor commented on reactChat/src/entities/Chat/Chat.tsx
> +        {/*</p>*/}
В Pull Request не должно быть закомментированного кода. Код либо нужен, либо не нужен.

2024-11-20 12:31 UTC, nelkor commented on reactChat/src/entities/User/model/User.slice.ts
> +import { fetchCurrentUser, fetchUsers } from '@/entities/User/model/User.thunk';
Ах да, и ещё: импортировать из текущего слайса в себя можно только относительными путями. Иначе получается, как тут, импорт из сущности в сущность, что невозможно по правилам FSD.

2024-11-20 12:31 UTC, nelkor commented on reactChat/src/shared/components/Input/hooks/useInput.ts
> +    }
Чтобы не дублировать вызов функции, в таких местах предпочтительнее писать так.

```suggestion
  setInnerType(innerType === 'text' ? 'password' : 'text')
```

2024-11-28 17:12 UTC, nelkor approved these changes
На будущее: не надо ругаться на пользователя, что он не заполнил поле, если он уже взял поле в фокус. Вот если он ушёл с него, то да, можно написать ошибку. После регистрации можно либо сразу авторизовать пользователя, либо хотя бы переместить на страницу входа. Сейчас же просто очищается форма и всё)

2024-12-06 22:38 UTC, HaseProgram commented
Аппрув, замечаний помимо озвученных не добавлю.
По 7, 9, 10 -12 баллов

2024-12-06 22:38 UTC, merged